### PR TITLE
A bunch of performance tweaks

### PR DESCRIPTION
**Pull request by drwahl**
I haven't verified this *doesn't* break Windows, but it fixes things
like the Windows tasks being applied (skipped, technically) on Linux
hosts, which in turn increases the performance of this role a ton. Along
with a couple other small tweaks, I took the runtime of this role from
45s down to 17s.

**Description of PR**
Performance enhancements for this role

**Type of change**
Feature Pull Request

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @drwahl 

I think you need to do a `git pull origin master` in your current branch and reapply/fix the changes. It seems you have created the `perftweaks` branch on a dated master branch and is causing merge conflicts.

May the force be with you (fixing merge issue 😉)!

**Comment by drwahl** [comment]
Oof... you are correct. I'm just about to head out of town, but I'll try to shore up this PR early next week.

**Comment by drwahl** [comment]
Life and work have gotten busy. I still intend to rebase my changes. Sorry for the delay.

**Comment by dj-wasabi** [comment]
No worries @drwahl , take your time! 👍

**Comment by dj-wasabi** [comment]
Hi @drwahl 

Are you able to resolve these issues soon? This repository will be closed soon, as it will be migrated to the Ansible Zabbix collection on a different namespace.

**Comment by drwahl** [comment]
Go ahead and migrate this code base. I'll need to re-work my patchset and haven't had time to focus on this lately.

**Pull request closed without merging**
