### PR TITLE
Removing some "older" os'es and added Fedora;Using new fact instead o…

### LINKED ISSUE #207: Role Should NOT Smash Ansible Facts
**Describe the bug**
This role smashes `ansible_distribution_major_version`. This should not happen.

```
- name: "Fedora | Modify ansible_distribution_major_version and zabbix_agent_conf_dir when Fedora"
  set_fact:
    ansible_distribution_major_version: 7
  when:
    - ansible_distribution == "Fedora"
```

As you can see, this task sets the distribution to something else. When connecting to a Fedora machine, one would expect this to be something along the lines of "27" or "28" or "29" (for more recent version of Fedora). By changing this to "7" does *not* do what it's supposed to be.

**Installation method/version**
I'm using this as a Github source at hash: d691a6bc0da5c8eb58b1d9d5e09c7ee7d300ac8e

However this appears to be present in master.
**Ansible Version**

2.7

**Targetted hosts**

* Fedora
**Expected behavior**
The role works as I would expect on Fedora, but it has unintended consequences. Any tasks that run *after* this task, even outside this role in the same playbook, has the wrong distribution version.

**Additional context**
I believe this was introduced in #199

### PR DESCRIPTION
**Pull request by dj-wasabi**
**Description of PR**

Removing some "older" os'es and added Fedora;Using new fact instead of an official Ansible fact.

**Type of change**

Bugfix Pull Request

**Fixes an issue**

Fixes #207

### CODE REVIEW

**Comment by fxfitz** [comment]
Overall, this does fix the issue described in #207 in the sense that that *one* task uses your new variable.

However, I think there are still some problems within the role that should be addressed:

* _Everywhere_ that is using `ansible_distribution_major_version` should now be switched to use the new variable: `zabbix_agent_distribution_major_version`. Without this, your role is trying to add the wrong repository:

```
TASK [dj-wasabi.zabbix-agent : RedHat | Install basic repo file] ***************fe
changed: [lab-css-fw-02.rogue] => (item={u'state': u'present', u'description': u'Zabbix Official Repository non-supported - $basearch', u'gpgcheck': 0, u'gpgkey': u'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX', u'baseurl': u'http://repo.zabbix.com/non-supported/rhel/27/$basearch/', u'name': u'zabbix-non-supported'})
```

That is because there is no RHEL 27 repository. If you used your new variable, this would not be the case.

* Additionally, you're still smashing Ansible variables in other tasks. If you need to change variables, you shouldn't be smashing the Ansible ones, but instead using one specific to your role.

For example, this task:

```
- name: "Fix facts for linuxmint - distribution release"
  set_fact:
    ansible_distribution_release: xenial
  when:
    - ansible_os_family == "Linuxmint"
    - ansible_distribution_release == "sonya" or ansible_distribution_release == "serena"
```

If someone used your role on Linuxmint, it would work fine (or so I assume). However if someone were to use another role after yours, one that expected `ansible_os_family` to be Linuxmint if it was Mint, then this screws up the next role for the same reason as #207 did.

**Comment by dj-wasabi** [comment]
@fxfitz Yes, you are absolutely right. Changing it now. Thanks! 👍

**Comment by dj-wasabi** [comment]
Hi @fxfitz 

I believe I have found all the properties now. Should be fine now.

**Comment by dj-wasabi** [comment]
@fxfitz thank you for testing! 👍 

Will merge and create a new release.

**Pull request merged**
