### PR TITLE
add sudo, and add zabbix-api dependency to readme.md

### PR DESCRIPTION
**Pull request by Savemech**
Please update this role;
because debian by default does not ship with sudo

### CODE REVIEW

**Comment by kostyrevaa** [comment]
I don't think that managing sudo package should be of any concern of this role

**Comment by Savemech** [comment]
But this playbook mention to use sudo, why then not take care and install it?

**Comment by kostyrevaa** [comment]
because one role - one software
but of course I'm just passing by - I'm not the author of this role

**Comment by Savemech** [comment]
well, but me lazy and i want to play my playbooks in any order, and if i did miss with playbook where roles like sudo or just ensure that sudo is installed and it is a latest one is missing, i wont to this particular playbook fail. Thats just my point. Since i did these addition to this repo; i did not care much, but newcomers prolly will met same "nah u have no sudo mate, go on and do another manual work, this is not ansible bad, its just this role".
Well just wait for @dj-wasabi  and solve this in some way.

**Comment by dj-wasabi** [comment]
Hi @Savemech 

I agree with @kostyrevaa It is not the responsibility of this role to install sudo. Sudo is an operating system tool which should already be available. Either by using pre tasks, when installing the operating systems itself or via sudo role. Otherwise this role should also be managing network interfaces, hosts files, dns configuration etc etc. 

The readme is something I can (and will if you update this PR with only the readme) accept.

Thank you.
Kind regards,

Werner

**Pull request closed without merging**
