### PR TITLE
Include Debian stretch in 3.4

### PR DESCRIPTION
**Pull request by rtgibbons**

### CODE REVIEW

**Comment by rtgibbons** [comment]
Actually , looking at http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix-release/ , we should remove trusty and xenial since they aren't included in 3.4

**Comment by dj-wasabi** [comment]
But xenial is the latest ubuntu release right? So why should this not be supported in the latest Zabbix release?

**Comment by rtgibbons** [comment]
It is, my bad - http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/

I was thinking Debian only when i wrote that.

**Comment by dj-wasabi** [comment]
ah, no worries. Thanks!

**Pull request merged**
