### PR TITLE
remove deprecated py scripts in library dir

### PR DESCRIPTION
**Pull request by mescanef**
Since zabbix_host and zabbix_hostmacro are available in the upstream, Ansible >=2.0, we can remove the content of library dir, to prevent Ansible from using these instead of the ones from the upstream.

// Edited.

### CODE REVIEW

**Comment by kostyrevaa** [comment]
oh my.
Why there's library/zabbix_host ?
when the very same module available from upstream since 2.0?

**Comment by mescanef** [comment]
Its a good question. Ok so I can propose here to remove the library/ directory for good.

**Comment by mescanef** [comment]
PR updated to remove these py scripts as there are in upstream equivalent modules and having them may cause the Ansible to not use the upstreams ones.

**Comment by dj-wasabi** [comment]
Thanks!

**Pull request merged**
