### PR TITLE
Pip packages install variable

### PR DESCRIPTION
**Pull request by rnsc**
**Description of PR**
This PR adds the `zabbix_install_pip_packages` so that we can disable the installation of pip packages when executing the role.
This is especially useful when you have a tight control on the environment you execute the role in.

**Type of change**
Feature Pull Request

Let me know if you think this is really out of scope.

### CODE REVIEW

**Comment by rnsc** [comment]
Hello @dj-wasabi 

Not sure if you've seen this PR :)
Does it make sense to you?
If it doesn't I'll keep a fork with that change for me :)

Thanks!

**Comment by dj-wasabi** [comment]
ah, sorry! My bad. Thanks! 👍

**Comment by rnsc** [comment]
> ah, sorry! My bad. Thanks!

Thanks @dj-wasabi, will you do a minor release on Ansible Galaxy in the coming days?

**Comment by rnsc** [comment]
Hello @dj-wasabi 

sorry for the noise, but will you make a release on Ansible Galaxy soon?
Otherwise, I'll just git clone the master of this repo for my project :)

Thanks,

**Comment by dj-wasabi** [comment]
Ah, will create one today! I totally forgot it again, my bad. I've created/sent some reminders so I won't forget it. :)

**Comment by dj-wasabi** [comment]
@rnsc 

I uploaded `1.6.1` to the Galaxy. Sorry for late reply/action, but nevertheless have fun! 😄

**Comment by rnsc** [comment]
@dj-wasabi cool, thanks!

**Pull request merged**
